categories: 分类
search: Search
tags: 标签
tagcloud: 标签云
prev: Prev
next: Next
comment: Comments
contents: Contents
archive_a: Archives
archive_b: "Archives: %s"
archive_date: "MMM YYYY"
page: Page %d
recent_posts: Recent Posts
menu: Menu
weibo: Weibo
links: Links
rss: RSS
doubanshow: Douban Show
github-card: Github Card
showsidebar: Show Sidebar
hidesidebar: Hide Sidebar
updated: Updated
totop: Back to Top
datepublished: Published
